# Generated by Django 3.1.5 on 2021-01-09 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_house', models.CharField(max_length=6, verbose_name='Номер дома')),
                ('a_building', models.IntegerField(blank=True, verbose_name='Строение/корпус')),
                ('a_entrances', models.IntegerField(default=1, verbose_name='Количество подъездов')),
            ],
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_street', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название улицы')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_module', models.CharField(db_index=True, max_length=4, unique=True, verbose_name='Номер модуля')),
                ('m_entrance', models.IntegerField(verbose_name='Подъезд')),
                ('m_height', models.IntegerField(verbose_name='Высота установки')),
                ('m_start', models.DateField(auto_now_add=True, verbose_name='Дата установки')),
                ('m_is_active', models.BooleanField(default=True, verbose_name='Состояние')),
                ('m_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgarb.addresses', verbose_name='Адрес')),
            ],
        ),
        migrations.AddField(
            model_name='addresses',
            name='a_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appgarb.streets', verbose_name='Название улицы'),
        ),
    ]
