# Generated by Django 3.1.5 on 2021-01-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='id',
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_module',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер модуля'),
        ),
    ]
