# Generated by Django 3.1.5 on 2021-01-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0002_auto_20210110_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ['a_street', 'a_house', 'a_building'], 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='streets',
            options={'ordering': ['s_street'], 'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
        migrations.AddField(
            model_name='modules',
            name='m_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Модуль'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='addresses',
            unique_together={('a_street', 'a_house', 'a_building')},
        ),
        migrations.AlterUniqueTogether(
            name='modules',
            unique_together={('m_addr', 'm_entrance')},
        ),
        migrations.RemoveField(
            model_name='modules',
            name='m_module',
        ),
    ]
