# Generated by Django 3.1.5 on 2021-01-10 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0003_auto_20210110_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modules',
            options={'ordering': ['m_id'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AddField(
            model_name='addresses',
            name='a_slug',
            field=models.SlugField(default='default_name', max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules',
            name='m_slug',
            field=models.SlugField(default='default_name', max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresses',
            name='a_house',
            field=models.CharField(max_length=10, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='a_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='appgarb.streets', verbose_name='Название улицы'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='appgarb.addresses', verbose_name='Адрес'),
        ),
    ]
