# Generated by Django 3.1.5 on 2021-01-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0004_auto_20210110_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='streets',
            name='s_slug',
            field=models.SlugField(default='default_name', max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
