# Generated by Django 3.1.5 on 2021-01-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0005_streets_s_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modules',
            options={'ordering': ['m_module'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.RemoveField(
            model_name='modules',
            name='m_id',
        ),
        migrations.AddField(
            model_name='modules',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules',
            name='m_module',
            field=models.CharField(default='1', max_length=4, verbose_name='Модуль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_entrance',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_height',
            field=models.PositiveSmallIntegerField(verbose_name='Высота установки'),
        ),
    ]
