# Generated by Django 3.1.5 on 2021-01-11 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0006_auto_20210111_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='m_building',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='modules',
            name='m_house',
            field=models.CharField(default='1', max_length=10, verbose_name='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules',
            name='m_street',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='appgarb.streets', verbose_name='Название улицы'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='modules',
            unique_together={('m_street', 'm_house', 'm_building', 'm_entrance')},
        ),
        migrations.RemoveField(
            model_name='modules',
            name='m_addr',
        ),
    ]
