# Generated by Django 3.1.5 on 2021-01-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0007_auto_20210111_0724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
