# Generated by Django 3.1.5 on 2021-01-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0008_delete_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='m_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='appgarb.streets', verbose_name='Название улицы'),
        ),
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_alarm', models.DateTimeField(verbose_name='Дата и время')),
                ('f_temp', models.PositiveSmallIntegerField(verbose_name='Температура')),
                ('f_smoke', models.PositiveSmallIntegerField(verbose_name='Задымленность')),
                ('f_slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('f_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire', to='appgarb.modules', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Пожарная тревога',
                'verbose_name_plural': 'Пожарная тревога',
                'ordering': ['f_module', 'f_alarm'],
                'unique_together': {('f_module', 'f_alarm')},
            },
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(verbose_name='Дата измерения')),
                ('c_curr', models.PositiveSmallIntegerField(verbose_name='Уровень наполнения')),
                ('c_slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('c_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='appgarb.modules', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Контейнер',
                'verbose_name_plural': 'Контейнеры',
                'ordering': ['c_module', 'c_date'],
                'unique_together': {('c_module', 'c_date')},
            },
        ),
    ]
