# Generated by Django 3.1.5 on 2021-01-12 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0010_auto_20210112_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 9, 29, 17, 437171), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_module',
            field=models.CharField(db_index=True, max_length=4, verbose_name='Модуль'),
        ),
    ]
