# Generated by Django 3.1.5 on 2021-01-13 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0011_auto_20210112_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 3, 44, 55, 132310), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_start',
            field=models.DateField(default=datetime.date(2021, 1, 13), verbose_name='Дата установки'),
        ),
    ]
