# Generated by Django 3.1.5 on 2021-01-13 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0012_auto_20210113_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containers',
            name='c_slug',
        ),
        migrations.RemoveField(
            model_name='fire',
            name='f_slug',
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 3, 59, 52, 391184), verbose_name='Дата измерения'),
        ),
    ]
