# Generated by Django 3.1.5 on 2021-01-13 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0013_auto_20210113_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 4, 15, 2, 29215), verbose_name='Дата измерения'),
        ),
    ]
