# Generated by Django 3.1.5 on 2021-01-16 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0014_auto_20210113_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 11, 56, 55, 456493), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_start',
            field=models.DateField(default=datetime.date(2021, 1, 16), verbose_name='Дата установки'),
        ),
    ]
