# Generated by Django 3.1.5 on 2021-01-17 04:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0015_auto_20210116_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 4, 21, 27, 49294), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contain', to='appgarb.modules', verbose_name='Контейнер'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_start',
            field=models.DateField(default=datetime.date(2021, 1, 17), verbose_name='Дата установки'),
        ),
    ]
