# Generated by Django 3.1.5 on 2021-01-17 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0017_auto_20210117_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 4, 50, 39, 980126), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_cont',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Тип контейнера'),
        ),
    ]
