# Generated by Django 3.1.4 on 2021-01-20 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0019_auto_20210120_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='containers',
            name='c_is_collected',
            field=models.BooleanField(default=False, verbose_name='Мусор вывезен'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 17, 27, 5, 300585), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contain', to='appgarb.modules', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_cont',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Тип контейнера, в %'),
        ),
        migrations.CreateModel(
            name='Analitics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateTimeField(default=datetime.datetime(2021, 1, 20, 17, 27, 5, 301584), verbose_name='Дата вывоза')),
                ('a_period', models.PositiveSmallIntegerField(verbose_name='Период наполнения, в днях')),
                ('a_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analitic', to='appgarb.modules', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
                'ordering': ['a_module', 'a_date'],
                'unique_together': {('a_module', 'a_date')},
            },
        ),
    ]
