# Generated by Django 3.1.4 on 2021-01-20 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0020_auto_20210120_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitics',
            name='a_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 17, 37, 40, 785303), verbose_name='Дата вывоза'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 17, 37, 40, 785303), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_cont',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Высота контейнера, в см'),
        ),
    ]
