# Generated by Django 3.1.4 on 2021-01-20 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0022_auto_20210120_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitics',
            name='a_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 20, 19, 54, 17652), verbose_name='Дата вывоза'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_curr',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Уровень наполнения, в %'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 20, 19, 54, 16652), verbose_name='Дата измерения'),
        ),
    ]
