# Generated by Django 3.1.4 on 2021-01-21 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0024_auto_20210120_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitics',
            name='a_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 11, 8, 35, 411048), verbose_name='Дата вывоза'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 6, 0), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgarb.modules', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='fire',
            name='f_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgarb.modules', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_start',
            field=models.DateField(default=datetime.date(2021, 1, 21), verbose_name='Дата установки'),
        ),
    ]
