# Generated by Django 3.1.5 on 2021-01-27 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0025_auto_20210121_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='analitics',
            name='a_fullness',
            field=models.PositiveSmallIntegerField(blank=True, default=100, verbose_name='Уровень наполнения, в %'),
        ),
        migrations.AddField(
            model_name='modules',
            name='m_pipe',
            field=models.PositiveSmallIntegerField(default=150, verbose_name='Высота мусоропровода'),
        ),
        migrations.AlterField(
            model_name='analitics',
            name='a_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 13, 40, 19, 955240), verbose_name='Дата вывоза'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 6, 0), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_start',
            field=models.DateField(default=datetime.date(2021, 1, 27), verbose_name='Дата установки'),
        ),
        migrations.AlterUniqueTogether(
            name='containers',
            unique_together={('c_module', 'c_date', 'c_curr')},
        ),
    ]
