# Generated by Django 3.1.5 on 2021-01-27 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0026_auto_20210127_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitics',
            name='a_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 13, 41, 15, 607427), verbose_name='Дата вывоза'),
        ),
    ]
