# Generated by Django 3.1.5 on 2021-01-27 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0028_auto_20210127_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitics',
            name='a_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 16, 37, 32, 705196), verbose_name='Дата вывоза'),
        ),
        migrations.AlterField(
            model_name='analitics',
            name='a_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgarb.modules', verbose_name='Модуль'),
        ),
        migrations.AlterUniqueTogether(
            name='containers',
            unique_together={('c_module', 'c_date')},
        ),
    ]
