# Generated by Django 3.1.5 on 2021-02-03 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0032_auto_20210202_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitics',
            name='a_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 16, 33, 57, 884329), verbose_name='Дата вывоза'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_curr',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Дистанция до мусора, см'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 6, 0), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_start',
            field=models.DateField(default=datetime.date(2021, 2, 3), verbose_name='Дата установки'),
        ),
        migrations.AlterUniqueTogether(
            name='containers',
            unique_together=set(),
        ),
    ]
