# Generated by Django 3.1.5 on 2021-02-03 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0033_auto_20210203_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitics',
            name='a_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 16, 36, 5, 690959), verbose_name='Дата вывоза'),
        ),
        migrations.AlterUniqueTogether(
            name='containers',
            unique_together={('c_module', 'c_date', 'c_is_collected')},
        ),
    ]
