# Generated by Django 3.1.5 on 2021-02-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0036_auto_20210212_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='c_incr',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Суточный прирост, %'),
        ),
    ]
