# Generated by Django 3.1.5 on 2021-02-13 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0037_auto_20210212_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='analitics',
            name='a_average',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Среднесуточный прирост, %'),
        ),
        migrations.AlterField(
            model_name='analitics',
            name='a_date',
            field=models.DateTimeField(default=datetime.date(2021, 2, 13), verbose_name='Дата вывоза'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 6, 0), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_start',
            field=models.DateField(default=datetime.date(2021, 2, 13), verbose_name='Дата установки'),
        ),
    ]
