# Generated by Django 3.1.5 on 2021-02-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0038_auto_20210213_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitics',
            name='a_average',
            field=models.FloatField(default=0, verbose_name='Среднесуточный прирост, %'),
        ),
    ]
