# Generated by Django 3.1.5 on 2021-02-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0039_auto_20210213_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitics',
            name='a_average',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3, verbose_name='Среднесуточный прирост, %'),
        ),
    ]
