# Generated by Django 3.1.6 on 2021-02-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0044_remove_streets_s_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methods',
            options={'verbose_name': 'Метод', 'verbose_name_plural': 'Методы'},
        ),
        migrations.RenameField(
            model_name='methods',
            old_name='me_methods',
            new_name='me_method',
        ),
    ]
