# Generated by Django 3.1.6 on 2021-02-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0045_auto_20210223_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methods',
            options={'ordering': ['id'], 'verbose_name': 'Метод', 'verbose_name_plural': 'Методы'},
        ),
        migrations.AlterField(
            model_name='methods',
            name='me_method',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Название метода'),
        ),
    ]
