# Generated by Django 3.1.5 on 2021-03-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0047_auto_20210306_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='m_method',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='appgarb.methods', verbose_name='Название метода'),
            preserve_default=False,
        ),
    ]
