# Generated by Django 3.1.5 on 2021-03-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0048_modules_m_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='m_method',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='appgarb.methods', verbose_name='Название метода'),
        ),
    ]
