# Generated by Django 3.1.5 on 2021-03-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0049_auto_20210306_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='m_params',
            field=models.TextField(default='[]', verbose_name='Параметры метода'),
        ),
    ]
