# Generated by Django 3.1.5 on 2021-03-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0050_modules_m_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='m_params',
            field=models.TextField(default='{}', verbose_name='Параметры метода'),
        ),
    ]
