# Generated by Django 3.1.5 on 2021-04-07 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgarb', '0052_auto_20210307_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analitics',
            name='a_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 0, 0), verbose_name='Дата вывоза'),
        ),
        migrations.AlterField(
            model_name='containers',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 6, 0), verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='fire',
            name='f_smoke',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Задымленность'),
        ),
        migrations.AlterField(
            model_name='fire',
            name='f_temp',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_plan',
            field=models.DateField(default=datetime.date(2021, 4, 7), verbose_name='Плановая дата вывоза'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='m_start',
            field=models.DateField(default=datetime.date(2021, 4, 7), verbose_name='Дата установки'),
        ),
    ]
